language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

services:
  - docker

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=diegolopmon/simple-vulnerable-webapp
- docker build -t diegolopmon/simple-vulnerable-webapp .
- docker tag diegolopmon/simple-vulnerable-webapp simple-vulnerable-webapp:$TAG
- docker push simple-vulnerable-webapp:$TAG